# Generated by Django 5.0.1 on 2024-06-05 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_relationalproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationalproduct",
            name="size",
        ),
    ]
